# Generated by Django 5.0.6 on 2024-07-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servo',
            new_name='posicion',
        ),
    ]
