# Generated by Django 5.0.6 on 2024-07-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_administrador_visitante_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
