# Generated by Django 5.0.6 on 2024-07-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_administrador_correo_alter_visitante_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitante',
            new_name='Usuario',
        ),
    ]
