# Generated by Django 5.0.6 on 2024-07-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_administrador_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Usuario',
        ),
    ]
