# Generated by Django 5.0.6 on 2024-07-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_administrador_visitante_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Usuarios',
        ),
    ]
